### ISSUE TITLE
CourseFragment drawMarker crash

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#260]
```
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
...
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
       at com.pennapps.labs.pennmobile.CourseFragment.drawMarker(CourseFragment.java:136)
       at com.pennapps.labs.pennmobile.CourseFragment.access$000(CourseFragment.java:31)
       at com.pennapps.labs.pennmobile.CourseFragment$1.call(CourseFragment.java:124)
       at com.pennapps.labs.pennmobile.CourseFragment$1.call(CourseFragment.java:120)
```

**Comment by jasontsh** [comment]
Clicks are being passed into the registrar fragment view
