### ISSUE TITLE
FragmentTransact illegal state exception

### ISSUE THREAD

**Issue by jasontsh** [pennlabs/penn-mobile-android#344]
`Fatal Exception: java.lang.IllegalStateException: Could not execute method of the activity
       at android.view.View$1.onClick(View.java:4298)
       at android.view.View.performClick(View.java:5254)`

`Caused by java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1500)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1518)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:634)`

`com.pennapps.labs.pennmobile.MainActivity.fragmentTransact (MainActivity.java:342)
com.pennapps.labs.pennmobile.MainActivity.getPermission (MainActivity.java:331)
com.pennapps.labs.pennmobile.MainActivity.navigateLayout (MainActivity.java:206)
com.pennapps.labs.pennmobile.MainActivity.onHomeButtonClick (MainActivity.java:241)`

**Comment by jasontsh** [comment]
Fixed...
