### ISSUE TITLE
Crashes in DiningInfoFragment

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#380]
21 crashes were reported in the last month from the DiningInfoFragment, app version 1.9.0, and since the file hasn't changed much since then I'm going to assume the bug is still in the wild.

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pennapps.labs.pennmobile/com.pennapps.labs.pennmobile.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.pennapps.labs.pennmobile.classes.Venue.allHours()' on a null object reference
...
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.pennapps.labs.pennmobile.classes.Venue.allHours()' on a null object reference
       at com.pennapps.labs.pennmobile.DiningInfoFragment.fillInfo(DiningInfoFragment.java:108)
       at com.pennapps.labs.pennmobile.DiningInfoFragment.onCreateView(DiningInfoFragment.java:65)
...
```

**Comment by jasontsh** [comment]
Fixed
