### ISSUE TITLE
Runtime Exception in DiningInfoFragment

### ISSUE THREAD

**Issue by adelq** [pennlabs/penn-mobile-android#391]
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.pennapps.labs.pennmobile/com.pennapps.labs.pennmobile.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.pennapps.labs.pennmobile.classes.Venue.allHours()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3319)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
       at android.app.ActivityThread.access$1100(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.pennapps.labs.pennmobile.classes.Venue.allHours()' on a null object reference
       at com.pennapps.labs.pennmobile.DiningInfoFragment.fillInfo(DiningInfoFragment.java:108)
       at com.pennapps.labs.pennmobile.DiningInfoFragment.onCreateView(DiningInfoFragment.java:65)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2046)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:174)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:598)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1266)
       at android.app.Activity.performStart(Activity.java:6943)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3276)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
       at android.app.ActivityThread.access$1100(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by jasontsh** [comment]
Fixed.
