### ISSUE TITLE
NullPointer in dining (Fabric #259)

### ISSUE THREAD

**Issue by jasontsh** [pennlabs/penn-mobile-android#412]
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.pennapps.labs.pennmobile.classes.Venue.allHours()' on a null object reference
       at com.pennapps.labs.pennmobile.DiningInfoFragment.fillInfo(DiningInfoFragment.java:108)
       at com.pennapps.labs.pennmobile.DiningInfoFragment.onCreateView(DiningInfoFragment.java:65)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)

This should be an easy null check fix

**Comment by jasontsh** [comment]
Fixed
