### ISSUE TITLE
Null pointer in SearchFavTab

### ISSUE THREAD

**Issue by jasontsh** [pennlabs/penn-mobile-android#413]
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference
       at com.pennapps.labs.pennmobile.SearchFavoriteTab.notFavoriteInit(SearchFavoriteTab.java:66)
       at com.pennapps.labs.pennmobile.RegistrarTab.initList(RegistrarTab.java:204)
       at com.pennapps.labs.pennmobile.SearchFavoriteFragment$1.onPageSelected(SearchFavoriteFragment.java:128)
       at android.support.v4.view.ViewPager.dispatchOnPageSelected(ViewPager.java:1856)
       at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:604)

The reason for this is because initList is called in createView where butterknife hasn't bound the views yet.

**Comment by jasontsh** [comment]
Fixed.
